# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-22 21:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('belt_reviewer_app', '0002_auto_20180322_1335'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='liked_users',
        ),
        migrations.RemoveField(
            model_name='book',
            name='uploader',
        ),
        migrations.DeleteModel(
            name='Book',
        ),
    ]
