# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-23 17:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes_app', '0003_quote_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='favorite_users',
            field=models.ManyToManyField(related_name='favorite_quote', to='users_app.User'),
        ),
    ]
